# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python310:
      python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install pipenv
    pipenv requirements --dev >> requirements.txt
    pip install -r requirements.txt
    pip install pytest-azurepipelines
  displayName: 'Install dependencies'

- script: |
    pre-commit run --all-files
  displayName: 'pre-commit'

- script: |
    coverage erase
    coverage run -m pytest tests
    coverage report
    coverage xml
  displayName: 'run tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-output.xml'
    testRunTitle: 'Publish test results'
    